// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQU-oHy0EDkDuAN6sbWlKb_I6DNFctmqI',
    appId: '1:37791790941:web:a1aa0b63df02679b371ab4',
    messagingSenderId: '37791790941',
    projectId: 'koraa-teem',
    authDomain: 'koraa-teem.firebaseapp.com',
    storageBucket: 'koraa-teem.firebasestorage.app',
    measurementId: 'G-0XC4VM0W6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV5P0Q9LCTqlvsMCKA2M_STVbhGO4jBew',
    appId: '1:37791790941:android:64220f868a0c8855371ab4',
    messagingSenderId: '37791790941',
    projectId: 'koraa-teem',
    storageBucket: 'koraa-teem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-KHHlYp9VKViG_c-Xt0NteHWVmpQ_cy8',
    appId: '1:37791790941:ios:4a05de2a23d144f7371ab4',
    messagingSenderId: '37791790941',
    projectId: 'koraa-teem',
    storageBucket: 'koraa-teem.firebasestorage.app',
    iosBundleId: 'com.example.korateem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-KHHlYp9VKViG_c-Xt0NteHWVmpQ_cy8',
    appId: '1:37791790941:ios:4a05de2a23d144f7371ab4',
    messagingSenderId: '37791790941',
    projectId: 'koraa-teem',
    storageBucket: 'koraa-teem.firebasestorage.app',
    iosBundleId: 'com.example.korateem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQU-oHy0EDkDuAN6sbWlKb_I6DNFctmqI',
    appId: '1:37791790941:web:bdd8cf16e70f793e371ab4',
    messagingSenderId: '37791790941',
    projectId: 'koraa-teem',
    authDomain: 'koraa-teem.firebaseapp.com',
    storageBucket: 'koraa-teem.firebasestorage.app',
    measurementId: 'G-BSBHFMHGF8',
  );
}
